#!/bin/bash

set -e

cd "$(dirname "$(readlink -f "$0")")"

prefix=~/
relpwd="${PWD#$prefix}"

find -type f | while read f; do

    f="${f:2}"

    [[ "$f" = .* || install = "$f" || project.arid = "$f" ]] && continue

    path=~/".$f"

    [[ -e "$path" ]] && {
        echo -n 'Skip: '
        ls --color "$path"
        continue
    } >&2

    esc="$(echo "$f" | tr -cd / | sed s:/:../:g)"

    ln -Tsfv "$esc$relpwd/$f" "$path"

done
