#!/bin/bash

set -e

cd "$(dirname "$($(which greadlink || which readlink) -f "$0")")"

prefix=~/
relpwd="${PWD#$prefix}"

$(which gfind || which find) -type f | while read f; do

    f="${f:2}"

    [[ "$f" = .* || install = "$f" || project.arid = "$f" ]] && continue

    path=~/".$f"

    [[ -e "$path" || ! -e "$(dirname "$path")" ]] && {
        echo -n 'Skip: '
        $(which gls || which ls) --color "$path" || true
        continue
    } >&2

    esc="$(echo "$f" | tr -cd / | sed s:/:../:g)"

    $(which gln || which ln) -Tsfv "$esc$relpwd/$f" "$path"

done
