#!/bin/bash

set -e

cd "$(dirname "$(readlink -f "$0")")"

prefix=~/
relpwd="${PWD#$prefix}"

for f in *; do

    [[ install = "$f" || project.arid = "$f" ]] && continue

    path=~/".$f"

    [[ -e "$path" ]] && {
        echo -n 'Skip: '
        ls --color "$path"
        continue
    } >&2

    ln -Tsfv "$relpwd/$f" "$path"

done
